### PR TITLE
Hii Where to add the configurations

### PR DESCRIPTION
**Pull request by santhoshrajuvysyaraju**
Hi i have installed your plugin from marketplace but i wont find the block in image tab => History Element i won,t find any sub tab to compare in the market place it is said that no configurations are needed but it is not displayed anything on my server.

Please tell me if it needs configurations that may helpful to me

### CODE REVIEW

**Comment by efge** [comment]
Please use https://answers.nuxeo.com for questions.

**Comment by santhoshrajuvysyaraju** [comment]
I Have Posted in That too but not getting any response from support

**Comment by efge** [comment]
Well here you posted a bogus Pull Request and that's definitely not the way to do it. Please don't misuse GitHub.

**Comment by santhoshrajuvysyaraju** [comment]
i have searched for issues tab but not found in your projects. so i used like this of course it is my mistake only

**Comment by efge** [comment]
Yes this is on purpose, https://answers.nuxeo.com should be used instead.

**Comment by santhoshrajuvysyaraju** [comment]
ok Thanks for INFO. and nuxeo-diff tag is not available in the specified site

**Pull request closed without merging**
